apiVersion: v2
name: atlas
version: 1.0.0
appVersion: 0.2.0
description: Atlas delivers automated secure communications between Prometheus and Thanos Sidecars.
dependencies:
- name: envoy
  version: 1.2.0
  repository: https://charts.goatlas.io