apiVersion: v1
appVersion: 1.18.3
description: Envoy is an open source edge and service proxy, designed for cloud-native applications.
home: https://goatlas.io/
keywords:
- envoy
- proxy
- atlas
name: envoy
sources:
- https://github.com/goatlas-io/atlas
version: 1.0.0
